# Generated by Django 2.1.4 on 2019-07-19 01:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Department',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('classification', models.CharField(blank=True, choices=[('ID', 'Instruction and Department Research'), ('OA', 'Organized Activities'), ('OR', 'Organized Research'), ('PS', 'Public Service'), ('LI', 'Libraries'), ('SS', 'Student Services'), ('MP', 'Maintenance and Operation of Physical Plant'), ('GA', 'General Administration'), ('GI', 'General Institutional Services'), ('AE', 'Auxilary Enterprises'), ('HC', 'Hospitals and Clinics'), ('SF', 'Scholarships and Fellowships'), ('AC', 'Additional Classifications')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('name', models.CharField(max_length=128, unique=True)),
                ('short_name', models.CharField(max_length=16)),
                ('classification', models.CharField(blank=True, choices=[('AG', 'Agriculture, Forestry, Fishing and Hunting'), ('MI', 'Mining, Quarrying, and Oil and Gas Extraction'), ('UT', 'Utilities'), ('CO', 'Construction'), ('MF', 'Manufacturing'), ('WS', 'Wholesale Trade'), ('RT', 'Retail Trade'), ('TR', 'Transportation and Warehousing'), ('IN', 'Information'), ('FI', 'Finance and Insurance'), ('RE', 'Real Estate and Rental and Leasing'), ('SC', 'Professional, Scientific, and Technical Services'), ('MG', 'Management of Companies and Enterprises'), ('AD', 'Administrative and Support and Waste Management and Remediation Services'), ('ED', 'Educational Services'), ('HC', 'Health Care and Social Assistance'), ('AR', 'Arts, Entertainment, and Recreation'), ('HS', 'Accommodation and Food Services'), ('GV', 'Public Administration'), ('OT', 'Other Services')], max_length=2, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_creation', models.DateField(auto_now_add=True)),
                ('record_update', models.DateField(auto_now=True)),
                ('cwid', models.CharField(blank=True, max_length=16, null=True, unique=True)),
                ('preferred_name', models.CharField(blank=True, max_length=128, null=True)),
                ('first_name', models.CharField(max_length=32)),
                ('last_name', models.CharField(max_length=32)),
                ('pronoun', models.CharField(blank=True, choices=[('HH', 'He/Him/His'), ('SH', 'She/Her/Hers'), ('TT', 'They/Them/Theirs'), ('ZZ', 'Zie/Zim/Zir'), ('OT', 'Other identification')], max_length=2, null=True)),
                ('title', models.CharField(blank=True, choices=[('DR', 'Dr'), ('MR', 'Mr'), ('MS', 'Mrs'), ('MI', 'Miss'), ('MZ', 'Ms'), ('RV', 'Rev'), ('SR', 'Sir')], max_length=2, null=True)),
                ('email_primary', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Primary email address')),
                ('email_secondary', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Secondary email address')),
                ('phone', models.CharField(blank=True, max_length=32, null=True)),
                ('comments', models.TextField(blank=True, null=True)),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Department')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Organization')),
            ],
            options={
                'verbose_name': 'Person',
                'verbose_name_plural': 'People',
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128, unique=True)),
            ],
        ),
        migrations.AddField(
            model_name='person',
            name='role',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='persons.Role'),
        ),
    ]
